version: "3.8"

services:
    app:
        build:
            context: .
            dockerfile: docker/php/Dockerfile
        image: laravel-app
        container_name: api-food
        working_dir: /var/www
        volumes:
            - .:/var/www
        depends_on:
            - mysql
        # command: >
        #     sh -c "
        #       composer install --no-interaction --prefer-dist &&
        #       php artisan migrate --force &&
        #       php-fpm
        #     "

    nginx:
        image: nginx:alpine
        container_name: nginx
        ports:
            - "8080:80"
        volumes:
            - .:/var/www
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app

    mysql:
        image: mysql:8
        container_name: mysql
        restart: always
        ports:
            - "3306:3306"
        environment:
            MYSQL_DATABASE: laravel
            MYSQL_ROOT_PASSWORD: root
        volumes:
            - mysql_data:/var/lib/mysql

    mailhog:
        image: mailhog/mailhog
        container_name: mailhog
        ports:
            - "8025:8025"

volumes:
    mysql_data:
